var modd=angular.module('railapp',['ngRoute','railservice']);
modd.config(function($routeProvider)
{
	$routeProvider
		.when("/",{
			redirectTo:'/train'
		})
		.when('/train',{
			templateUrl:'train.html',
			controller:'TrainCtrl'
		})
		.when('/reservation',{
			templateUrl:'reservation.html',
			controller:'ReservationCtrl'
		})
});
modd.controller('RailCtrl',function($scope,$routeParams){
	$scope.setActive=function(type)
	{
		$scope.trainActive='';
		$scope.reservationActive='';
		$scope[type+'Active']='active';
	}
});
modd.controller('TrainCtrl',function($scope,Train,Reservation,$http){
	$scope.setActive('train');
	$scope.train;
	$http.get('trains.json').success(function(data,status){
	});
	console.log($scope.train);
	$scope.reserve=function(code)
	{
		Reservation.add()
	}
});
modd.controller('ReservationCtrl',function($scope,Reservation,Train){
	$scope.setActive('reservation');
});